swagger: "2.0"
info:
  version: "1.0.0"
  title: "tala API"
host: "localhost"
basePath: "/tala/api/v1"
schemes:
  - http
paths:
  /nodes/:
    get:
      summary: "ノード情報を取得(一覧)します"
      description: "ノード情報を取得(一覧)します"
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Node'

  /nodes/{id}/:
    get:
      summary: "ノード情報を取得します"
      description: "ノード情報を取得します"
      parameters:
        - name: "id"
          in: "path"
          description: "Node ID"
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Node'

  /nodes/{id}/status/:
    post:
      summary: "対象のノードの状態を変更します"
      description: ""
      parameters:
        - name: "id"
          in: "path"
          description: "Node ID"
          required: true
          type: integer
        - name: "body"
          in: body
          schema:
            properties:
              status:
                type: string
                description: "変更後の状態"
                example: "INSTALLING"
                enum: ["INSTALLING", "READY"]
      responses:
        200:
          description: OK

  /nodes/{id}/power/:
    post:
      summary: "対象のノードの電源状態を変更します"
      description: ""
      parameters:
        - name: "id"
          in: "path"
          description: "Node ID"
          required: true
          type: integer
        - name: "body"
          in: body
          schema:
            properties:
              status:
                type: string
                description: "変更後の電源状態"
                example: "ON"
                enum: ["ON", "OFF"]
      responses:
        200:
          description: OK

  /nodes/{id}/metrics/:
    get:
      summary: "対象のノードのメトリクス情報を取得します"
      description: ""
      parameters:
        - name: "id"
          in: "path"
          description: "Node ID"
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                metrics_type:
                  type: string
                  description: "メトリクスタイプ"
                value:
                  type: string
                  description: "値"
                date:
                  type: string
                  description: "値を取得した時間"
                unit:
                  type: string
                  description: "単位"

    post:
      summary: "対象のノードのメトリクス情報を保存します"
      description: ""
      parameters:
        - name: "id"
          in: "path"
          description: "Node ID"
          required: true
          type: integer
        - name: "body"
          in: body
          schema:
            properties:
              metrics_type:
                type: string
                description: "メトリクスタイプ"
              value:
                type: string
                description: "値"
              date:
                type: string
                description: "値を取得した時間"
              unit:
                type: string
                description: "単位"
      responses:
        200:
          description: OK


  /nodes/{id}/metrics/{metrics_type}/:
    get:
      summary: "対象のノードのメトリクスごとのメトリクス情報を取得します"
      description: ""
      parameters:
        - name: "id"
          in: "path"
          description: "Node ID"
          required: true
          type: integer
        - name: "metrics_type"
          in: "path"
          description: "Metrics Type"
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                metrics_type:
                  type: string
                  description: "メトリクスタイプ"
                value:
                  type: string
                  description: "値"
                date:
                  type: string
                  description: "値を取得した時間"
                unit:
                  type: string
                  description: "単位"

  /users/:
    get:
      summary: "ユーザ一覧を取得します"
      description: ""
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                  description: "User ID"
                  example: 1
                username:
                  type: string
                  description: "Username"
                  example: "Hans Schmidt"

  /users/{id}/:
    get:
      summary: "ユーザ詳細情報を取得します"
      description: ""
      parameters:
        - name: "id"
          in: "path"
          description: "User ID"
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            properties:
              id:
                type: integer
                description: "User ID"
                example: 1
              username:
                type: string
                description: "Username"
                example: "Hans Schmidt"
              ssh_public_key:
                type: string
                description: "SSH Public Key"

definitions:
  Node:
    type: object
    properties:
      id:
        type: integer
        description: "Node ID"
        example: 1
      name:
        type: string
        description: "名前"
        example: "Node01"
      description:
        type: string
        description: "説明"
        example: "一号機"
      hostname:
        type: string
        description: "ホスト名"
        example: "hogehoge.example.com"
      ip_address:
        type: string
        description: "IPアドレス"
        example: "192.168.25.3"
      mac_address:
        type: string
        description: "MACアドレス"
        example: "FF:FF:FF:FF:FF:FF"
      os:
        type: string
        description: "OS"
      status:
        type: string
        description: "ステータス"
      type:
        type: string
        description: "Node TYPE"
      ipmi_ip_address:
        type: string
        description: "IPMI IPアドレス"
        example: "192.168.125.3"
      ipmi_mac_address:
        type: string
        description: "IPMI MACアドレス"
        example: "FF:FF:FF:FF:FF:FF"
      ipmi_user_name:
        type: string
        description: "IPMI ユーザ名"
        example: "admin"
      ipmi_password:
        type: string
        description: "IPMI パスワード"
        example: "admin"
