# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_type', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('value', models.CharField(max_length=20)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Node')),
            ],
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='host_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='core.Node'),
        ),
    ]
