# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('mac_address', models.CharField(blank=True, max_length=200)),
                ('os', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='hostname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='ipmi_mac_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='mac_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='os',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='node',
            name='ipmi_ip_address',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='node',
            name='ipmi_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='ipmi_user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='virtualmachines',
            name='host_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Node'),
        ),
    ]
