# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170902_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachines',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
