# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170906_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='power',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='allocate_cpu',
            field=models.CharField(blank=True, max_length=200, verbose_name='割り当てCPUコア数'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='allocate_disk',
            field=models.CharField(blank=True, max_length=200, verbose_name='割り当てディスク容量'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='allocate_memory',
            field=models.CharField(blank=True, max_length=200, verbose_name='割り当てメモリ容量'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='power',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
