# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171118_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='vnc_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='VNCポート番号'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='allocate_cpu',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=200, verbose_name='割り当てCPUコア数'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='allocate_disk',
            field=models.CharField(blank=True, choices=[('10', '10GB'), ('20', '20GB'), ('50', '50GB'), ('100', '100GB')], max_length=200, verbose_name='割り当てディスク容量'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='allocate_memory',
            field=models.CharField(blank=True, choices=[('536870912', '512MB'), ('1073741824', '1GB'), ('2147483648', '2GB'), ('4294967296', '4GB')], max_length=200, verbose_name='割り当てメモリ容量'),
        ),
    ]
