# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170902_0837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VirtualMachines',
            new_name='VirtualMachine',
        ),
        migrations.AlterField(
            model_name='node',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='node',
            name='ipmi_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
