# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171118_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='vnc_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='VNCポート番号'),
        ),
    ]
