# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_node_vnc_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='password',
            field=models.CharField(blank=True, max_length=200, verbose_name='管理ユーザパスワード'),
        ),
    ]
