# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171201_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('mac_address', models.CharField(blank=True, max_length=200)),
                ('os', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('power', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='管理ユーザパスワード')),
                ('docker_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='core.Node')),
            ],
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='host_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='core.Node'),
        ),
    ]
